# Generated by Django 3.2.1 on 2024-06-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art_work',
            old_name='title',
            new_name='art_title',
        ),
        migrations.RemoveField(
            model_name='art_work',
            name='art_id',
        ),
        migrations.AddField(
            model_name='art_work',
            name='art_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='art_work',
            name='art_image',
            field=models.ImageField(blank=True, upload_to='art_images/'),
        ),
        migrations.AddField(
            model_name='art_work',
            name='art_name',
            field=models.CharField(default='null', max_length=90),
        ),
    ]
