# Generated by Django 3.2.1 on 2024-06-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_auto_20240621_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_work',
            name='art_name',
        ),
    ]
