# Generated by Django 3.2.1 on 2024-06-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_remove_art_work_art_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_work',
            name='artiste',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
