# Generated by Django 3.2.1 on 2024-07-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0006_profile_type_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Type_User',
        ),
    ]
